[build]
  command = "npm install -g cross-env && cross-env CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
